const PROVINCES = [
    { name: "Ha Noi", code: "HN", latitude: 21.028511, longitude: 105.804817, image: require('../assets/background/HaNoi.jpg') },
    // { name: "Ho Chi Minh City", code: "HCM", latitude: 10.762622, longitude: 106.660172, image: require('../assets/background/HoChiMinhCity.jpg') },
    // { name: "Da Nang", code: "DN", latitude: 16.047079, longitude: 108.206230, image: require('../assets/background/DaNang.jpg') },
    // { name: "Hai Phong", code: "HP", latitude: 20.865139, longitude: 106.683830, image: require('../assets/background/HaiPhong.jpg') },
    { name: "Can Tho", code: "CT", latitude: 10.045162, longitude: 105.746857, image: require('../assets/background/CanTho.jpg') },
    // { name: "Hue", code: "HUE", latitude: 16.463713, longitude: 107.590866, image: require('../assets/background/Hue.jpg') },
    { name: "Bac Giang", code: "BG", latitude: 21.301, longitude: 106.633, image: require('../assets/background/BacGiang.jpg') },
    // { name: "Bac Kan", code: "BK", latitude: 22.166, longitude: 105.833, image: require('../assets/background/BacKan.jpg') },
    // { name: "Bac Lieu", code: "BL", latitude: 9.283, longitude: 105.716, image: require('../assets/background/BacLieu.jpg') },
    // { name: "Bac Ninh", code: "BN", latitude: 21.183, longitude: 106.05, image: require('../assets/background/BacNinh.jpg') },
    // { name: "Ben Tre", code: "BT", latitude: 10.25, longitude: 106.383, image: require('../assets/background/BenTre.jpg') },
    // { name: "Binh Dinh", code: "BD", latitude: 13.783, longitude: 109.219, image: require('../assets/background/BinhDinh.jpg') },
    // { name: "Binh Duong", code: "BDG", latitude: 10.980, longitude: 106.651, image: require('../assets/background/BinhDuong.jpg') },
    // { name: "Binh Phuoc", code: "BP", latitude: 11.751, longitude: 106.723, image: require('../assets/background/BinhPhuoc.jpg') },
    // { name: "Binh Thuan", code: "BTH", latitude: 10.933, longitude: 108.100, image: require('../assets/background/BinhThuan.jpg') },
    // { name: "Ca Mau", code: "CM", latitude: 9.177, longitude: 105.150, image: require('../assets/background/CaMau.jpg') },
    // { name: "Cao Bang", code: "CB", latitude: 22.666, longitude: 106.250, image: require('../assets/background/CaoBang.jpg') },
    // { name: "Dak Lak", code: "DL", latitude: 12.667, longitude: 108.050, image: require('../assets/background/DakLak.jpg') },
    // { name: "Dak Nong", code: "DN2", latitude: 12.000, longitude: 107.683, image: require('../assets/background/DakNong.jpg') },
    // { name: "Dien Bien", code: "DB", latitude: 21.383, longitude: 103.017, image: require('../assets/background/DienBien.jpg') },
    // { name: "Dong Nai", code: "DN", latitude: 10.945, longitude: 107.006, image: require('../assets/background/DongNai.jpg') },
    // { name: "Dong Thap", code: "DT", latitude: 10.480, longitude: 105.636, image: require('../assets/background/DongThap.jpg') },
    // { name: "Gia Lai", code: "GL", latitude: 13.983, longitude: 108.000, image: require('../assets/background/GiaLai.jpg') },
    // { name: "Ha Giang", code: "HG", latitude: 22.833, longitude: 104.983, image: require('../assets/background/HaGiang.jpg') },
    // { name: "Ha Nam", code: "HNA", latitude: 20.542, longitude: 105.911, image: require('../assets/background/HaNam.jpg') },
    // { name: "Ha Tinh", code: "HT", latitude: 18.355, longitude: 105.887, image: require('../assets/background/HaTinh.jpg') },
    // { name: "Hai Duong", code: "HD", latitude: 20.939, longitude: 106.331, image: require('../assets/background/HaiDuong.jpg') },
    // { name: "Hau Giang", code: "HG2", latitude: 9.783, longitude: 105.467, image: require('../assets/background/HauGiang.jpg') },
    // { name: "Hoa Binh", code: "HB", latitude: 20.817, longitude: 105.337, image: require('../assets/background/HoaBinh.jpg') },
    // { name: "Hung Yen", code: "HY", latitude: 20.646, longitude: 106.051, image: require('../assets/background/HungYen.jpg') },
    // { name: "Khanh Hoa", code: "KH", latitude: 12.252, longitude: 109.196, image: require('../assets/background/KhanhHoa.jpg') },
    // { name: "Kien Giang", code: "KG", latitude: 10.015, longitude: 105.091, image: require('../assets/background/KienGiang.jpg') },
    // { name: "Kon Tum", code: "KT", latitude: 14.350, longitude: 108.000, image: require('../assets/background/KonTum.jpg') },
    // { name: "Lai Chau", code: "LC", latitude: 22.050, longitude: 103.150, image: require('../assets/background/LaiChau.jpg') },
    // { name: "Lam Dong", code: "LD", latitude: 11.940, longitude: 108.458, image: require('../assets/background/LamDong.jpg') },
    // { name: "Lang Son", code: "LS", latitude: 21.853, longitude: 106.758, image: require('../assets/background/LangSon.jpg') },
    // { name: "Lao Cai", code: "LCI", latitude: 22.483, longitude: 103.967, image: require('../assets/background/LaoCai.jpg') },
    // { name: "Long An", code: "LA", latitude: 10.695, longitude: 106.245, image: require('../assets/background/LongAn.jpg') },
    // { name: "Nam Dinh", code: "ND", latitude: 20.433, longitude: 106.167, image: require('../assets/background/NamDinh.jpg') },
    // { name: "Nghe An", code: "NA", latitude: 18.673, longitude: 105.692, image: require('../assets/background/NgheAn.jpg') },
    // { name: "Ninh Binh", code: "NB", latitude: 20.253, longitude: 105.974, image: require('../assets/background/NinhBinh.jpg') },
    // { name: "Ninh Thuan", code: "NT", latitude: 11.567, longitude: 108.983, image: require('../assets/background/NinhThuan.jpg') },
    // { name: "Phu Tho", code: "PT", latitude: 21.333, longitude: 105.217, image: require('../assets/background/PhuTho.jpg') },
    // { name: "Phu Yen", code: "PY", latitude: 13.089, longitude: 109.092, image: require('../assets/background/PhuYen.jpg') },
    // { name: "Quang Binh", code: "QB", latitude: 17.500, longitude: 106.600, image: require('../assets/background/QuangBinh.jpg') },
    { name: "Quang Nam", code: "QNA", latitude: 15.573, longitude: 108.474, image: require('../assets/background/QuangNam.jpg') },
    // { name: "Quang Ngai", code: "QNG", latitude: 15.120, longitude: 108.792, image: require('../assets/background/QuangNgai.jpg') },
    // { name: "Quang Ninh", code: "QN", latitude: 20.960, longitude: 107.100, image: require('../assets/background/QuangNinh.jpg') },
    // { name: "Quang Tri", code: "QT", latitude: 16.750, longitude: 107.183, image: require('../assets/background/QuangTri.jpg') },
    // { name: "Soc Trang", code: "ST", latitude: 9.603, longitude: 105.980, image: require('../assets/background/SocTrang.jpg') },
    // { name: "Son La", code: "SL", latitude: 21.325, longitude: 103.918, image: require('../assets/background/SonLa.jpg') },
    // { name: "Tay Ninh", code: "TN", latitude: 11.310, longitude: 106.098, image: require('../assets/background/TayNinh.jpg') },
    // { name: "Thai Binh", code: "TB", latitude: 20.445, longitude: 106.336, image: require('../assets/background/ThaiBinh.jpg') },
    // { name: "Thai Nguyen", code: "TNG", latitude: 21.594, longitude: 105.848, image: require('../assets/background/ThaiNguyen.jpg') },
    // { name: "Thanh Hoa", code: "TH", latitude: 19.807, longitude: 105.776, image: require('../assets/background/ThanhHoa.jpg') },
    // { name: "Thua Thien Hue", code: "TTH", latitude: 16.463, longitude: 107.590, image: require('../assets/background/ThuaThienHue.jpg') },
    // { name: "Tien Giang", code: "TG", latitude: 10.365, longitude: 106.361, image: require('../assets/background/TienGiang.jpg') },
    // { name: "Tra Vinh", code: "TV", latitude: 9.934, longitude: 106.345, image: require('../assets/background/TraVinh.jpg') },
    // { name: "Tuyen Quang", code: "TQ", latitude: 21.817, longitude: 105.217, image: require('../assets/background/TuyenQuang.jpg') },
    // { name: "Vinh Long", code: "VL", latitude: 10.243, longitude: 105.958, image: require('../assets/background/VinhLong.jpg') },
    // { name: "Vinh Phuc", code: "VP", latitude: 21.308, longitude: 105.604, image: require('../assets/background/VinhPhuc.jpg') },
    // { name: "Yen Bai", code: "YB", latitude: 21.705, longitude: 104.870, image: require('../assets/background/YenBai.jpg') },
];

export default PROVINCES;
