// styles/profile.styles.js
import { StyleSheet } from "react-native";
import { ThemeType } from "../../themes/theme";

// const createProfileStyles = (colors: ThemeType) =>
//   StyleSheet.create({
//     container: {
//       flex: 1,
//       backgroundColor: colors.background,
//       // padding: 16,
//       paddingBottom: 0,
//     },
//     loadingContainer: {
//       flex: 1,
//       justifyContent: "center",
//       alignItems: "center",
//       backgroundColor: colors.background,
//     },
//     profileHeader: {
//       flexDirection: "row",
//       alignItems: "center",
//       backgroundColor: colors.cardBackground,
//       borderRadius: 16,
//       padding: 16,
//       marginBottom: 16,
//       shadowColor: colors.black,
//       shadowOffset: { width: 0, height: 2 },
//       shadowOpacity: 0.1,
//       shadowRadius: 8,
//       elevation: 3,
//       borderWidth: 1,
//       borderColor: colors.border,
//     },
//     profileImage: {
//       width: 80,
//       height: 80,
//       borderRadius: 40,
//       marginRight: 16,
//     },
//     profileInfo: {
//       flex: 1,
//     },
//     username: {
//       fontSize: 20,
//       fontWeight: "700",
//       color: colors.textPrimary,
//       marginBottom: 4,
//     },
//     email: {
//       fontSize: 14,
//       color: colors.textSecondary,
//       marginBottom: 4,
//     },
//     memberSince: {
//       fontSize: 12,
//       color: colors.textSecondary,
//     },
//     logoutButton: {
//       backgroundColor: colors.primary,
//       borderRadius: 12,
//       padding: 12,
//       flexDirection: "row",
//       alignItems: "center",
//       justifyContent: "center",
//       marginBottom: 24,
//       shadowColor: colors.black,
//       shadowOffset: { width: 0, height: 2 },
//       shadowOpacity: 0.1,
//       shadowRadius: 4,
//       elevation: 2,
//     },
//     logoutText: {
//       color: colors.white,
//       fontWeight: "600",
//       marginLeft: 8,
//     },
//     booksHeader: {
//       flexDirection: "row",
//       justifyContent: "space-between",
//       alignItems: "center",
//       marginBottom: 16,
//     },
//     booksTitle: {
//       fontSize: 18,
//       fontWeight: "700",
//       color: colors.textPrimary,
//     },
//     booksCount: {
//       fontSize: 14,
//       color: colors.textSecondary,
//     },
//     booksList: {
//       paddingBottom: 20,
//     },
//     bookItem: {
//       flexDirection: "row",
//       backgroundColor: colors.cardBackground,
//       borderRadius: 12,
//       padding: 12,
//       marginBottom: 12,
//       shadowColor: colors.black,
//       shadowOffset: { width: 0, height: 1 },
//       shadowOpacity: 0.1,
//       shadowRadius: 4,
//       elevation: 2,
//       borderWidth: 1,
//       borderColor: colors.border,
//     },
//     bookImage: {
//       width: 70,
//       height: 100,
//       borderRadius: 8,
//       marginRight: 12,
//     },
//     bookInfo: {
//       flex: 1,
//       justifyContent: "space-between",
//     },
//     bookTitle: {
//       fontSize: 16,
//       fontWeight: "600",
//       color: colors.textPrimary,
//       marginBottom: 4,
//     },
//     ratingContainer: {
//       flexDirection: "row",
//       marginBottom: 4,
//     },
//     bookCaption: {
//       fontSize: 14,
//       color: colors.textDark,
//       marginBottom: 4,
//       flex: 1,
//     },
//     bookDate: {
//       fontSize: 12,
//       color: colors.textSecondary,
//     },
//     deleteButton: {
//       padding: 8,
//       justifyContent: "center",
//     },
//     emptyContainer: {
//       alignItems: "center",
//       justifyContent: "center",
//       padding: 40,
//       marginTop: 20,
//     },
//     emptyText: {
//       fontSize: 16,
//       fontWeight: "600",
//       color: colors.textPrimary,
//       marginTop: 16,
//       marginBottom: 20,
//       textAlign: "center",
//     },
//     addButton: {
//       backgroundColor: colors.primary,
//       borderRadius: 12,
//       paddingVertical: 12,
//       paddingHorizontal: 20,
//       shadowColor: colors.black,
//       shadowOffset: { width: 0, height: 2 },
//       shadowOpacity: 0.1,
//       shadowRadius: 4,
//       elevation: 2,
//     },
//     addButtonText: {
//       color: colors.white,
//       fontWeight: "600",
//       fontSize: 14,
//     },

//     avatar: {
//       width: 70,
//       height: 70,
//       borderRadius: 35,
//       marginRight: 12,
//       borderWidth: 2,
//       borderColor: "#4f46e5",
//     },
//     modalOverlay: {
//       flex: 1,
//       backgroundColor: "rgba(0,0,0,0.5)",
//       justifyContent: "center",
//       alignItems: "center",
//     },

//     modalContent: {
//       backgroundColor: colors.white,
//       width: "85%",
//       borderRadius: 16,
//       padding: 20,
//       elevation: 10,
//     },

//     modalTitle: {
//       fontSize: 18,
//       fontWeight: "bold",
//       color: colors.textPrimary,
//       marginBottom: 12,
//       textAlign: "center",
//     },

//     input: {
//       borderWidth: 1,
//       borderColor: colors.border,
//       borderRadius: 10,
//       padding: 10,
//       marginBottom: 12,
//       fontSize: 14,
//       color: colors.textPrimary,
//     },

//     modalButtons: {
//       flexDirection: "row",
//       justifyContent: "flex-end",
//       marginTop: 10,
//     },

//     saveButton: {
//       backgroundColor: colors.primary,
//       paddingVertical: 10,
//       paddingHorizontal: 20,
//       borderRadius: 10,
//       marginLeft: 10,
//     },

//     saveButtonText: {
//       color: colors.white,
//       fontWeight: "bold",
//       fontSize: 14,
//     },

//     cancelButton: {
//       backgroundColor: colors.border,
//       paddingVertical: 10,
//       paddingHorizontal: 20,
//       borderRadius: 10,
//     },

//     cancelButtonText: {
//       color: colors.textPrimary,
//       fontWeight: "bold",
//       fontSize: 14,
//     },
//     statsText: {
//       fontSize: 14,
//       color: colors.textSecondary,
//       marginTop: 2,
//     },
//     statsContainer: {
//       marginTop: 8,
//       paddingVertical: 6,
//       paddingHorizontal: 10,
//       backgroundColor: "#f0f0f0",
//       borderRadius: 8,
//     },
//     placesContainer: {
//     marginTop: 20,
//   },
//   placesHeader: {
//     fontSize: 18,
//     fontWeight: "700",
//     marginBottom: 8,
//     color: "#111827",
//   },
//   placeItem: {
//     backgroundColor: "#fff",
//     padding: 12,
//     marginBottom: 8,
//     borderRadius: 12,
//     fontSize: 15,
//     shadowColor: "#000",
//     shadowOpacity: 0.05,
//     shadowRadius: 2,
//     elevation: 2,
//   },
//   });



const createProfileStyles = (colors) => StyleSheet.create({

  //  container: {
//       flex: 1,
//       backgroundColor: colors.background,
//       // padding: 16,
//       paddingBottom: 0,
//     },
//     loadingContainer: {
//       flex: 1,
//       justifyContent: "center",
//       alignItems: "center",
//       backgroundColor: colors.background,
//     },
//     profileHeader: {
//       flexDirection: "row",
//       alignItems: "center",
//       backgroundColor: colors.cardBackground,
//       borderRadius: 16,
//       padding: 16,
//       marginBottom: 16,
//       shadowColor: colors.black,
//       shadowOffset: { width: 0, height: 2 },
//       shadowOpacity: 0.1,
//       shadowRadius: 8,
//       elevation: 3,
//       borderWidth: 1,
//       borderColor: colors.border,
//     },
//     profileImage: {
//       width: 80,
//       height: 80,
//       borderRadius: 40,
//       marginRight: 16,
//     },
//     profileInfo: {
//       flex: 1,
//     },
//     username: {
//       fontSize: 20,
//       fontWeight: "700",
//       color: colors.textPrimary,
//       marginBottom: 4,
//     },
//     email: {
//       fontSize: 14,
//       color: colors.textSecondary,
//       marginBottom: 4,
//     },
//     memberSince: {
//       fontSize: 12,
//       color: colors.textSecondary,
//     },
//     logoutButton: {
//       backgroundColor: colors.primary,
//       borderRadius: 12,
//       padding: 12,
//       flexDirection: "row",
//       alignItems: "center",
//       justifyContent: "center",
//       marginBottom: 24,
//       shadowColor: colors.black,
//       shadowOffset: { width: 0, height: 2 },
//       shadowOpacity: 0.1,
//       shadowRadius: 4,
//       elevation: 2,
//     },
//     logoutText: {
//       color: colors.white,
//       fontWeight: "600",
//       marginLeft: 8,
//     },
//     booksHeader: {
//       flexDirection: "row",
//       justifyContent: "space-between",
//       alignItems: "center",
//       marginBottom: 16,
//     },
//     booksTitle: {
//       fontSize: 18,
//       fontWeight: "700",
//       color: colors.textPrimary,
//     },
//     booksCount: {
//       fontSize: 14,
//       color: colors.textSecondary,
//     },
//     booksList: {
//       paddingBottom: 20,
//     },
//     bookItem: {
//       flexDirection: "row",
//       backgroundColor: colors.cardBackground,
//       borderRadius: 12,
//       padding: 12,
//       marginBottom: 12,
//       shadowColor: colors.black,
//       shadowOffset: { width: 0, height: 1 },
//       shadowOpacity: 0.1,
//       shadowRadius: 4,
//       elevation: 2,
//       borderWidth: 1,
//       borderColor: colors.border,
//     },
//     bookImage: {
//       width: 70,
//       height: 100,
//       borderRadius: 8,
//       marginRight: 12,
//     },
//     bookInfo: {
//       flex: 1,
//       justifyContent: "space-between",
//     },
//     bookTitle: {
//       fontSize: 16,
//       fontWeight: "600",
//       color: colors.textPrimary,
//       marginBottom: 4,
//     },
//     ratingContainer: {
//       flexDirection: "row",
//       marginBottom: 4,
//     },
//     bookCaption: {
//       fontSize: 14,
//       color: colors.textDark,
//       marginBottom: 4,
//       flex: 1,
//     },
//     bookDate: {
//       fontSize: 12,
//       color: colors.textSecondary,
//     },
//     deleteButton: {
//       padding: 8,
//       justifyContent: "center",
//     },
//     emptyContainer: {
//       alignItems: "center",
//       justifyContent: "center",
//       padding: 40,
//       marginTop: 20,
//     },
//     emptyText: {
//       fontSize: 16,
//       fontWeight: "600",
//       color: colors.textPrimary,
//       marginTop: 16,
//       marginBottom: 20,
//       textAlign: "center",
//     },
//     addButton: {
//       backgroundColor: colors.primary,
//       borderRadius: 12,
//       paddingVertical: 12,
//       paddingHorizontal: 20,
//       shadowColor: colors.black,
//       shadowOffset: { width: 0, height: 2 },
//       shadowOpacity: 0.1,
//       shadowRadius: 4,
//       elevation: 2,
//     },
//     addButtonText: {
//       color: colors.white,
//       fontWeight: "600",
//       fontSize: 14,
//     },

//     avatar: {
//       width: 70,
//       height: 70,
//       borderRadius: 35,
//       marginRight: 12,
//       borderWidth: 2,
//       borderColor: "#4f46e5",
//     },
//     modalOverlay: {
//       flex: 1,
//       backgroundColor: "rgba(0,0,0,0.5)",
//       justifyContent: "center",
//       alignItems: "center",
//     },

//     modalContent: {
//       backgroundColor: colors.white,
//       width: "85%",
//       borderRadius: 16,
//       padding: 20,
//       elevation: 10,
//     },

//     modalTitle: {
//       fontSize: 18,
//       fontWeight: "bold",
//       color: colors.textPrimary,
//       marginBottom: 12,
//       textAlign: "center",
//     },

//     input: {
//       borderWidth: 1,
//       borderColor: colors.border,
//       borderRadius: 10,
//       padding: 10,
//       marginBottom: 12,
//       fontSize: 14,
//       color: colors.textPrimary,
//     },

//     modalButtons: {
//       flexDirection: "row",
//       justifyContent: "flex-end",
//       marginTop: 10,
//     },

//     saveButton: {
//       backgroundColor: colors.primary,
//       paddingVertical: 10,
//       paddingHorizontal: 20,
//       borderRadius: 10,
//       marginLeft: 10,
//     },

//     saveButtonText: {
//       color: colors.white,
//       fontWeight: "bold",
//       fontSize: 14,
//     },

//     cancelButton: {
//       backgroundColor: colors.border,
//       paddingVertical: 10,
//       paddingHorizontal: 20,
//       borderRadius: 10,
//     },

//     cancelButtonText: {
//       color: colors.textPrimary,
//       fontWeight: "bold",
//       fontSize: 14,
//     },
//     statsText: {
//       fontSize: 14,
//       color: colors.textSecondary,
//       marginTop: 2,
//     },
//     statsContainer: {
//       marginTop: 8,
//       paddingVertical: 6,
//       paddingHorizontal: 10,
//       backgroundColor: "#f0f0f0",
//       borderRadius: 8,
//     },
    placesContainer: {
    marginTop: 20,
  },
//   placesHeader: {
//     fontSize: 18,
//     fontWeight: "700",
//     marginBottom: 8,
//     color: "#111827",
//   },
//   placeItem: {
//     backgroundColor: "#fff",
//     padding: 12,
//     marginBottom: 8,
//     borderRadius: 12,
//     fontSize: 15,
//     shadowColor: "#000",
//     shadowOpacity: 0.05,
//     shadowRadius: 2,
//     elevation: 2,
//   },

  container: {
    flex: 1,
    backgroundColor: colors.background || "#f8fafb",
    paddingTop: 5,
  },
  profileHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 24,
    paddingHorizontal: 18,
    backgroundColor: colors.card || "#fff",
    borderBottomWidth: 0.7,
    borderBottomColor: "#eaeef2",
    marginBottom: 8,
    elevation: 2,
    shadowColor: "#d9e8ff",
    borderRadius: 18,
  },
  avatar: {
    width: 76, height: 76,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: "#1676c1",
    marginBottom: 2,
    backgroundColor: "#eaf6ff",
  },
  username: {
    fontSize: 21,
    fontWeight: "bold",
    color: colors.primary || "#2586eb",
    marginBottom: 4,
  },
  email: {
    fontSize: 15,
    color: colors.textSecondary || "#6a8bae",
    marginBottom: 2,
  },
  statsText: {
    fontSize: 15,
    color: colors.textSecondary || "#666",
    marginBottom: 2,
    letterSpacing: 0.1,
  },
  tripsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 18,
    marginTop: 13,
    marginBottom: 0,
    minHeight: 35,
  },
  tripsTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.primary || "#2586eb",
    letterSpacing: 0.1,
  },
  tripsCount: {
    fontSize: 15,
    color: colors.textSecondary || "#999",
  },
  tripsList: {
    paddingHorizontal: 12,
    paddingBottom: 21,
    paddingTop: 6,
  },
  tripItem: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 17,
    paddingHorizontal: 11,
    paddingVertical: 12,
    alignItems: "center",
    elevation: 2,
    shadowColor: "#d1d7e2",
    marginBottom: 12,
    borderWidth: 1.1,
    borderColor: "#f0f4f8",
  },
  tripImage: {
    width: 67,
    height: 54,
    borderRadius: 8,
    marginRight: 9,
    backgroundColor: "#f7f8ff",
    borderWidth: 0.7,
    borderColor: "#e3ecf9",
  },
  tripTitle: {
    fontWeight: "bold",
    fontSize: 16.5,
    color: "#2292ca",
    marginBottom: 0,
  },
  emptyContainer: {
    justifyContent: "center", alignItems: "center",
    marginTop: 70, marginBottom: 30
  },
  emptyText: {
    marginTop: 11,
    color: "#8ea2c8",
    fontSize: 15.5,
    marginBottom: 16,
  },
  addButton: {
    marginTop: 10,
    backgroundColor: "#21b6f6", 
    paddingVertical: 12, 
    borderRadius: 11,
    width: 180, 
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#21b6f6",
    shadowOpacity: 0.17,
    elevation: 1.5,
  },
  addButtonText: {
    color: "#fff",
    fontWeight: "bold",
    marginLeft: 8,
    fontSize: 16,
    letterSpacing: 0.1,
  },
  logoutButton: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "center",
  alignSelf: "center",
  marginTop: 16,
  marginBottom: 6,
  backgroundColor: "#e53935", // Đỏ nhấn mạnh nhưng dịu, có thể thay màu nếu theme bạn tối hơn
  paddingVertical: 12,
  paddingHorizontal: 28,
  borderRadius: 14,
  elevation: 3,
  shadowColor: "#ef5350",
  shadowOpacity: 0.18,
  shadowOffset: { width: 1, height: 3 },
},
logoutText: {
  color: "#fff",
  fontWeight: "bold",
  fontSize: 17,
  letterSpacing: 0.7,
},

searchBarAnimated: {
  flexDirection: "row",
  alignItems: "center",
  backgroundColor: "#ecf7ff",
  borderRadius: 15,
  borderWidth: 1,
  borderColor: "#cdeafe",
  height: 34,
  overflow: "hidden",
  marginRight: 5
},

});


export default createProfileStyles;
